paper: 0.02
scissor: 0.02
MeatCan: -0.02
FishCan: 0.02
banana: -0.04
sauce: 0.07
clamp: 0.02
ball: 0.04
duck: -0.02
cola: 0.04
lock: 0.02
dice: 0.02
bowl: 0.02
tape: 0.02
pot: 0.02
pen: 0.02
E27: 0.02
E24: 0.02
fork: 0.02
Screwdriver: 0.02
Strawberry: 0.02
glass: 0.02
cup: 0.02
wrench: -0.02
gummies: 0.02
glue: -0.02
gloves: 0.02
t-shirt: 0.02
key: 0.02
mark: 0.02
book: 0.02
cookie: -0.02
red_mark: 0.03
brick: 0.02
tomato_cup: 0.04
blue_paper: 0.02
toothpaste: 0.02
coffee: 0.04
cube: -0.02
